"""Phase 04 -- functional motifs, neuron grouping and pathway diagrams.

Sub-phase 04A (this package) starts the layer: it reads a Phase 03 ``eigen.json``
and writes the canonical ``motifs.json`` + ``motifs.npz`` (+ ``motifs.data.json``)
with the per-mode signed motif structure.  Later sub-phases (04B-04D) populate the
neutral fields frozen here (links/families, groups, pathway) without changing the
schema.

Public surface (imported lazily so that
``python -m src.clustering.functional_motifs`` does not execute the module twice,
mirroring :mod:`src.parsing`, :mod:`src.matrices` and :mod:`src.spectral`):

* :func:`compute_participation` -- the ``(N, k)`` participation matrix (4 variants).
* :func:`motif_thresholds` / :func:`motif_membership` -- the threshold grid.
* :func:`extract_motif` / :func:`extract_motifs` -- the signed, ordered members.
* :func:`initial_families` -- the neutral k-singleton family partition.
* :func:`build_motif_analysis` -- artifact assembly from a Phase 03 spectrum.
* :func:`load_motifs` / :func:`load_sidecar_arrays` -- the entry points for 04B-04D
  and Phase 05 (canonical JSON, plus the verified ``.npz`` array cache).
* :func:`derive_region` / :func:`load_anatomy` / :func:`load_node_metadata` -- the
  region labels and the optional ``parsed_graph.json`` enrichment.
* :func:`write_artifact_set` -- persist the requested artifact set.
* :func:`main` -- the command line interface.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - import-time only for type checkers
    from src.clustering.functional_motifs import (
        CANONICAL_STEM,
        CODE_CONFIG,
        CODE_FAMILY_CONFLICT,
        CODE_INPUT_SCHEMA,
        CODE_MATRIX_MISMATCH,
        CODE_MATRIX_MISSING,
        CODE_MODE_WEIGHTS,
        CODE_NONFINITE,
        CODE_NO_LINKS,
        CODE_PARTITION,
        CODE_BACKGROUND,
        CODE_PATHWAY_SKIPPED,
        CODE_SINGLETON,
        CODE_ZERO_VECTOR,
        CODE_PAYLOAD_SCHEMA,
        CONFIG_KEYS,
        DEFAULT_ABSOLUTE_THRESHOLD,
        DEFAULT_MAX_MEMBERS,
        DEFAULT_MIN_MEMBERS,
        DEFAULT_PARTICIPATION,
        DEFAULT_PARTICIPATION_THRESHOLD,
        DEFAULT_QUANTILE,
        DEFAULT_RELATIVE_THRESHOLD,
        DEFAULT_THRESHOLD_METHOD,
        FAMILY_KEYS,
        GENERATOR,
        GRAPHML_EDGE_KEYS,
        GRAPHML_GRAPH_KEYS,
        GRAPHML_NODE_KEYS,
        GROUP_KEYS,
        INPUT_VARIANT_PREFIX,
        LINK_CLASSES,
        LINK_KEYS,
        MATRIX_INPUT_PREFIX,
        MEMBER_KEYS,
        METADATA_KEYS,
        MOTIF_CONFIG_FIELDS,
        MOTIF_KEYS,
        NEURON_PARTICIPATION_KEYS,
        NEUTRAL_PATHWAY,
        NODE_KEYS,
        OCCURRENCE_KEYS,
        PARTICIPATIONS,
        PATHWAY_KEYS,
        PATHWAY_THRESHOLD_SWEEP,
        PATHWAY_TOP_MODES,
        PATHWAY_WEIGHT_NORMALIZATION,
        PROVENANCE_KEYS,
        SAVE_DATA_KEYS,
        STAGE,
        THRESHOLD_METHODS,
        TOP_LEVEL_KEYS,
        XML_DECLARATION,
        Motif,
        MotifAnalysis,
        MotifConfig,
        MotifFamily,
        MotifLink,
        MotifMember,
        MotifValidationError,
        NeuronGroup,
        PathwayDiagram,
        PathwayEdge,
        PathwayNode,
        artifact_paths,
        build_argument_parser,
        build_motif_analysis,
        build_pathway,
        assign_groups,
        initial_group_labels,
        merge_similar_groups,
        split_large_groups,
        loadings_clustering,
        build_groups,
        group_from_labels,
        group_centroid,
        group_coherence,
        region_composition,
        build_sidecar_arrays,
        classify_link,
        compute_participation,
        derive_region,
        extract_motif,
        extract_motifs,
        family_members,
        filter_pathway_edges,
        graphml_edge_metadata,
        graphml_node_metadata,
        group_pair_contributions,
        initial_families,
        input_variant,
        load_anatomy,
        load_motifs,
        load_node_metadata,
        load_pathway_matrix,
        load_sidecar_arrays,
        main,
        merge_families,
        mode_outer_product,
        mode_weights,
        motif_links,
        motif_membership,
        motif_statistics,
        motif_thresholds,
        pathway_matrix_path,
        recurrence_table,
        render_statistics,
        render_summary_box,
        resolve_inputs,
        save_data_payload,
        sidecar_path,
        validate_motif_payload_schema,
        variant_stem,
        write_artifact_set,
        write_graphml_pathway,
        write_npz_atomic,
        write_sidecar,
    )

_MODULE_NAME = "src.clustering.functional_motifs"

__all__ = [
    "CANONICAL_STEM",
    "CODE_CONFIG",
    "CODE_FAMILY_CONFLICT",
    "CODE_INPUT_SCHEMA",
    "CODE_MATRIX_MISMATCH",
    "CODE_MATRIX_MISSING",
    "CODE_MODE_WEIGHTS",
    "CODE_NONFINITE",
    "CODE_NO_LINKS",
    "CODE_PARTITION",
    "CODE_BACKGROUND",
    "CODE_PATHWAY_SKIPPED",
    "CODE_SINGLETON",
    "CODE_ZERO_VECTOR",
    "CODE_PAYLOAD_SCHEMA",
    "CONFIG_KEYS",
    "DEFAULT_ABSOLUTE_THRESHOLD",
    "DEFAULT_MAX_MEMBERS",
    "DEFAULT_MIN_MEMBERS",
    "DEFAULT_PARTICIPATION",
    "DEFAULT_PARTICIPATION_THRESHOLD",
    "DEFAULT_QUANTILE",
    "DEFAULT_RELATIVE_THRESHOLD",
    "DEFAULT_THRESHOLD_METHOD",
    "FAMILY_KEYS",
    "GENERATOR",
    "GRAPHML_EDGE_KEYS",
    "GRAPHML_GRAPH_KEYS",
    "GRAPHML_NODE_KEYS",
    "GROUP_KEYS",
    "INPUT_VARIANT_PREFIX",
    "LINK_CLASSES",
    "LINK_KEYS",
    "MATRIX_INPUT_PREFIX",
    "MEMBER_KEYS",
    "METADATA_KEYS",
    "MOTIF_CONFIG_FIELDS",
    "MOTIF_KEYS",
    "NEURON_PARTICIPATION_KEYS",
    "NEUTRAL_PATHWAY",
    "NODE_KEYS",
    "OCCURRENCE_KEYS",
    "PARTICIPATIONS",
    "PATHWAY_KEYS",
    "PATHWAY_THRESHOLD_SWEEP",
    "PATHWAY_TOP_MODES",
    "PATHWAY_WEIGHT_NORMALIZATION",
    "PROVENANCE_KEYS",
    "SAVE_DATA_KEYS",
    "STAGE",
    "THRESHOLD_METHODS",
    "TOP_LEVEL_KEYS",
    "XML_DECLARATION",
    "Motif",
    "MotifAnalysis",
    "MotifConfig",
    "MotifFamily",
    "MotifLink",
    "MotifMember",
    "MotifValidationError",
    "NeuronGroup",
    "PathwayDiagram",
    "PathwayEdge",
    "PathwayNode",
    "artifact_paths",
    "build_argument_parser",
    "build_motif_analysis",
    "build_pathway",
    "assign_groups",
    "initial_group_labels",
    "merge_similar_groups",
    "split_large_groups",
    "loadings_clustering",
    "build_groups",
    "group_from_labels",
    "group_centroid",
    "group_coherence",
    "region_composition",
    "build_sidecar_arrays",
    "classify_link",
    "compute_participation",
    "derive_region",
    "extract_motif",
    "extract_motifs",
    "family_members",
    "filter_pathway_edges",
    "graphml_edge_metadata",
    "graphml_node_metadata",
    "group_pair_contributions",
    "initial_families",
    "input_variant",
    "load_anatomy",
    "load_motifs",
    "load_node_metadata",
    "load_pathway_matrix",
    "load_sidecar_arrays",
    "main",
    "merge_families",
    "mode_outer_product",
    "mode_weights",
    "motif_links",
    "motif_membership",
    "motif_statistics",
    "motif_thresholds",
    "pathway_matrix_path",
    "recurrence_table",
    "render_statistics",
    "render_summary_box",
    "resolve_inputs",
    "save_data_payload",
    "sidecar_path",
    "validate_motif_payload_schema",
    "variant_stem",
    "write_artifact_set",
    "write_graphml_pathway",
    "write_npz_atomic",
    "write_sidecar",
]


def __getattr__(name: str) -> Any:
    """Resolve the public names from :mod:`src.clustering.functional_motifs` on demand."""
    if name in __all__:
        module = importlib.import_module(_MODULE_NAME)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(__all__)
